openapi: 3.0.1
info:
  title: MyTestService
  version: v1
servers:
- url: /
security:
- bearerAuth: []
paths:
  /api/Values:
    get:
      operationId: Get
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - Values
      x-accepts: application/json
components:
  schemas:
    LoginModel:
      properties:
        username:
          type: string
        password:
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      description: JWT Authorization header
      in: header
      name: Authorization
      type: apiKey
x-original-swagger-version: "2.0"

